spring:
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      
logging:
  level:
    org:
      springframework: debug